site_name: AI Agent Builder Workshop
site_description: A workshop to learn about how to build and manage AI Agents using Microsoft Agent Framework. 
site_author: Rakesh Lakshminarayanana
site_url: https://binarytrails-ai.github.io/agent-builder-workshop

nav:
  - Welcome: index.md
  - Environment Setup: 00-setup_instructions.md
  - "LAB 1: Personalization": 01-lab-personalization.md
  - "LAB 2: Memory": 02-lab-memory.md
  - "LAB 3: Tools": 03-lab-tools.md
  - "LAB 3.1: Tool Error Handling": 03.1-lab-tool-error-handling.md
  - "LAB 4: Human Approval": 05-lab-human-approval.md
  - "LAB 5: Multi-Agent": 06-lab-multi-agent.md
  - "Finishing Up": finishing-up.md
  - Learning Resources: resources.md
  - Additional Resources:
    - Azure Resource Deployment: Resources/azure-resource-setup.md
    - Aspire Dashboard Setup: Resources/aspire-dashboard-setup.md
  - Feedback: feedback.md

plugins:
  - glightbox
  - include-markdown

theme:
  name: material
  logo: media/favicon.png
  favicon: media/favicon.png
  features:
    - navigation.instant
    - navigation.footer
    - content.code.copy
    - navigation.tabs.sticky
    - content.tabs.link

  # Change Font: https://squidfunk.github.io/mkdocs-material/setup/changing-the-fonts/?h=fonts
  # Google Fonts Supported By Default: https://fonts.google.com/
  font:
    code: Roboto Mono
    text: Roboto
  palette:
    - scheme: default # Light Mode
      primary: black
      accent: pink
      toggle:
        icon: material/brightness-2
        name: Switch to dark mode
    - scheme: slate # Dark Mode
      primary: amber
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 2
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html
  # - pymdownx.emoji:
  # emoji_index: !!python/name:material.extensions.emoji.twemoji
  # emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - css/custom.css

# mkdocs.yml
extra_javascript:
  - js/custom-nav.js
